
package app;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalog", targetNamespace = "http://app/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalog {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://app/", className = "app.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://app/", className = "app.GetProductsResponse")
    @Action(input = "http://app/ProductCatalog/getProductsRequest", output = "http://app/ProductCatalog/getProductsResponse")
    public List<String> getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://app/", className = "app.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://app/", className = "app.AddProductResponse")
    @Action(input = "http://app/ProductCatalog/addProductRequest", output = "http://app/ProductCatalog/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://app/", className = "app.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://app/", className = "app.GetProductCategoriesResponse")
    @Action(input = "http://app/ProductCatalog/getProductCategoriesRequest", output = "http://app/ProductCatalog/getProductCategoriesResponse")
    public List<String> getProductCategories();

}
